all: Galaxy Nebula BlackHole Mittu

CFLAGS=-g -O0 -Wall -ggdb
CC=gcc

Galaxy:
	$(CC) $(CFLAGS) Galaxy.c -o Galaxy
Nebula: 
	$(CC) $(CFLAGS) Nebula.c -o Nebula
BlackHole: 
	$(CC) $(CFLAGS) BlackHole.c -o BlackHole

clean:
	rm -f Galaxy Nebula BlackHole

