all: Millow Pillow Killow 
CFLAGS=-g -O0 -Wall -ggdb
CC=gcc

Millow:
	$(CC) $(CFLAGS) Millow.c -o Millow
Pillow: 
	$(CC) $(CFLAGS) Pillow.c -o Pillow
Killow:
	$(CC) $(CFLAGS) Killow.c -o Killow

clean:
	rm -f Millow Killow Pillow 

