all: Laltu Ittu Bittu Mittu

CFLAGS=-g -O0 -Wall -ggdb
CC=gcc

Laltu:
	$(CC) $(CFLAGS) Laltu.c -o Laltu
Ittu: 
	$(CC) $(CFLAGS) Ittu.c -o Ittu
Bittu: 
	$(CC) $(CFLAGS) Bittu.c -o Bittu
Mittu: 
	$(CC) $(CFLAGS) Mittu.c -o Mittu

clean:
	rm -f Laltu Ittu Bittu Mittu

