all: PipeCreator Minu Binu 
CFLAGS=-g -O0 -Wall -ggdb
CC=gcc

PipeCreator:
	$(CC) $(CFLAGS) PipeCreator.c -o PipeCreator
Minu: 
	$(CC) $(CFLAGS) Minu.c -o Minu
Binu:
	$(CC) $(CFLAGS) Binu.c -o Binu

clean:
	rm -f PipeCreator Binu Minu 

